### ISSUE TITLE
More efficient module importing script

### ISSUE THREAD

**Issue by stuffpicklesays** [estella144/parashell#1]
Hi Olive
replace the repetitive start with a more efficient script

imports = ['sys', 'itertools', 'datetime', 'os']
#put 

modules = {}
for x in imports:
    try:
        print("importing module ", x, '(', str(int(imports.index(x))+1),'/', len(imports)+1, ')')
        modules[x] = __import__(x)
        print("Successfully imported ", x, '.')
    except:
        print("Error importing ", x, '.')

#use modules["MODULENAME"].whateverfunctiontouse()

today = modules["datetime"].date.today()
print(today)

**Comment by estella144** [comment]
That might interfere with the pyinstaller compilation. Will still review.

**Comment by estella144** [comment]
That **will** interfere with the pyinstaller compilation. Also everyone uses lists of imports anyway. Got rid of the import debug statements in 0.2.3 development anyway ha. **That's a close!**
